# -*- coding: utf-8 -*-
"""Virtual_Screening_Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VruOKEuhSp2Fhk4IW6Dz-TTBlTIAN0qs
"""

# Virtual Screening Automation

!pip install rdkit-pypi chembl_webresource_client "numpy<2"

import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs
from chembl_webresource_client.new_client import new_client

# Reference ligand (Gefitinib, EGFR inhibitor)
ref_smiles = "COC1=CC2=C(C=C1)N=C(S2)NC3=CC=CC=C3F"
ref_mol = Chem.MolFromSmiles(ref_smiles)
ref_fp = AllChem.GetMorganFingerprintAsBitVect(ref_mol, 2, 2048)

# Fetch candidate molecules (first 100 approved drugs)
molecule = new_client.molecule
compounds = molecule.filter(max_phase=4)[:100]
df = pd.DataFrame(compounds)

# Compute similarity
def tanimoto(smi):
    mol = Chem.MolFromSmiles(smi)
    if mol:
        fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, 2048)
        return DataStructs.TanimotoSimilarity(fp, ref_fp)
    return None

df["similarity"] = df["molecule_structures"].apply(
    lambda x: tanimoto(x["canonical_smiles"]) if x else None
)

# Show top 5 hits
print(df[["molecule_chembl_id", "pref_name", "similarity"]]
      .sort_values("similarity", ascending=False)
      .head(5))